// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkillSwap.Platform.Shared.Infrastructure.Persistence.EntityFrameworkCore.Configuration;

#nullable disable

namespace SkillSwap.Platform.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SkillSwap.Platform.Discovery.Domain.Model.Aggregates.Tutor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Career")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<string>("MainSubject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Online")
                        .HasColumnType("tinyint(1)");

                    b.Property<double>("Rating")
                        .HasColumnType("double");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("int");

                    b.Property<string>("University")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Verified")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("tutors", (string)null);
                });

            modelBuilder.Entity("SkillSwap.Platform.Iam.Domain.Model.Aggregates.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SkillSwap.Platform.Learning.Domain.Model.Aggregates.Quiz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Course")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("quizzes", (string)null);
                });

            modelBuilder.Entity("SkillSwap.Platform.Learning.Domain.Model.Aggregates.QuizAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("QuizId")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<string>("SelectedAnswers")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<int>("Total")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("quiz_attempts", (string)null);
                });

            modelBuilder.Entity("SkillSwap.Platform.Moderation.Domain.Model.Aggregates.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Closed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("reports", (string)null);
                });

            modelBuilder.Entity("SkillSwap.Platform.Moderation.Domain.Model.Aggregates.Sanction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int");

                    b.Property<int>("ReportId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("sanctions", (string)null);
                });

            modelBuilder.Entity("SkillSwap.Platform.Payments.Domain.Model.Aggregates.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("WalletId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("SkillSwap.Platform.Payments.Domain.Model.Aggregates.Wallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("wallets", (string)null);
                });

            modelBuilder.Entity("SkillSwap.Platform.Reputation.Domain.Model.Aggregates.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReviewedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("reviews", (string)null);
                });

            modelBuilder.Entity("SkillSwap.Platform.Workspace.Domain.Model.Aggregates.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("QuizId")
                        .HasColumnType("int");

                    b.Property<string>("QuizTitle")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("SkillSwap.Platform.Workspace.Domain.Model.Aggregates.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("SkillSwap.Platform.Discovery.Domain.Model.Aggregates.Tutor", b =>
                {
                    b.OwnsOne("SkillSwap.Platform.Discovery.Domain.Model.ValueObjects.TutorId", "TutorUserId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<int>("UserId")
                                .HasColumnType("int")
                                .HasColumnName("UserId");

                            b1.HasKey("Id");

                            b1.ToTable("tutors");

                            b1.WithOwner()
                                .HasForeignKey("Id");
                        });

                    b.OwnsOne("SkillSwap.Platform.Discovery.Domain.Model.ValueObjects.TutorSkills", "TutorSkills", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<string>("Skills")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("Skills");

                            b1.HasKey("Id");

                            b1.ToTable("tutors");

                            b1.WithOwner()
                                .HasForeignKey("Id");
                        });

                    b.Navigation("TutorSkills")
                        .IsRequired();

                    b.Navigation("TutorUserId")
                        .IsRequired();
                });

            modelBuilder.Entity("SkillSwap.Platform.Learning.Domain.Model.Aggregates.Quiz", b =>
                {
                    b.OwnsOne("SkillSwap.Platform.Discovery.Domain.Model.ValueObjects.TutorId", "TutorId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<int>("UserId")
                                .HasColumnType("int")
                                .HasColumnName("TutorId");

                            b1.HasKey("Id");

                            b1.ToTable("quizzes");

                            b1.WithOwner()
                                .HasForeignKey("Id");
                        });

                    b.OwnsMany("SkillSwap.Platform.Learning.Domain.Model.ValueObjects.Question", "Questions", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<string>("Answers")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<int>("CorrectAnswer")
                                .HasColumnType("int");

                            b1.Property<string>("QuestionString")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<int>("QuizId")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("QuizId");

                            b1.ToTable("quiz_questions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("QuizId");
                        });

                    b.Navigation("Questions");

                    b.Navigation("TutorId")
                        .IsRequired();
                });

            modelBuilder.Entity("SkillSwap.Platform.Learning.Domain.Model.Aggregates.QuizAttempt", b =>
                {
                    b.OwnsOne("SkillSwap.Platform.Learning.Domain.Model.ValueObjects.LearnerId", "AttemptLearnerId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<int>("UserId")
                                .HasColumnType("int")
                                .HasColumnName("LearnerId");

                            b1.HasKey("Id");

                            b1.ToTable("quiz_attempts");

                            b1.WithOwner()
                                .HasForeignKey("Id");
                        });

                    b.Navigation("AttemptLearnerId")
                        .IsRequired();
                });

            modelBuilder.Entity("SkillSwap.Platform.Moderation.Domain.Model.Aggregates.Report", b =>
                {
                    b.OwnsOne("SkillSwap.Platform.Moderation.Domain.Model.ValueObjects.ReportedUserId", "ReportedUserId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<int>("UserId")
                                .HasColumnType("int")
                                .HasColumnName("ReportedUserId");

                            b1.HasKey("Id");

                            b1.ToTable("reports");

                            b1.WithOwner()
                                .HasForeignKey("Id");
                        });

                    b.OwnsOne("SkillSwap.Platform.Moderation.Domain.Model.ValueObjects.ReporterId", "ReporterUserId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<int>("UserId")
                                .HasColumnType("int")
                                .HasColumnName("ReporterUserId");

                            b1.HasKey("Id");

                            b1.ToTable("reports");

                            b1.WithOwner()
                                .HasForeignKey("Id");
                        });

                    b.OwnsOne("SkillSwap.Platform.Moderation.Domain.Model.ValueObjects.SessionId", "ReportSessionId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("SessionId");

                            b1.HasKey("Id");

                            b1.ToTable("reports");

                            b1.WithOwner()
                                .HasForeignKey("Id");
                        });

                    b.Navigation("ReportSessionId")
                        .IsRequired();

                    b.Navigation("ReportedUserId")
                        .IsRequired();

                    b.Navigation("ReporterUserId")
                        .IsRequired();
                });

            modelBuilder.Entity("SkillSwap.Platform.Moderation.Domain.Model.Aggregates.Sanction", b =>
                {
                    b.OwnsOne("SkillSwap.Platform.Moderation.Domain.Model.ValueObjects.SanctionedUserId", "SanctionedUserId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<int>("UserId")
                                .HasColumnType("int")
                                .HasColumnName("SanctionedUserId");

                            b1.HasKey("Id");

                            b1.ToTable("sanctions");

                            b1.WithOwner()
                                .HasForeignKey("Id");
                        });

                    b.Navigation("SanctionedUserId")
                        .IsRequired();
                });

            modelBuilder.Entity("SkillSwap.Platform.Payments.Domain.Model.Aggregates.Wallet", b =>
                {
                    b.OwnsOne("SkillSwap.Platform.Payments.Domain.Model.ValueObjects.OwnerId", "WalletOwnerId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<int>("UserId")
                                .HasColumnType("int")
                                .HasColumnName("OwnerId");

                            b1.HasKey("Id");

                            b1.ToTable("wallets");

                            b1.WithOwner()
                                .HasForeignKey("Id");
                        });

                    b.Navigation("WalletOwnerId")
                        .IsRequired();
                });

            modelBuilder.Entity("SkillSwap.Platform.Reputation.Domain.Model.Aggregates.Review", b =>
                {
                    b.OwnsOne("SkillSwap.Platform.Reputation.Domain.Model.ValueObjects.ReviewedTutorId", "ReviewedTutorId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<int>("TutorId")
                                .HasColumnType("int")
                                .HasColumnName("ReviewedTutorId");

                            b1.HasKey("Id");

                            b1.ToTable("reviews");

                            b1.WithOwner()
                                .HasForeignKey("Id");
                        });

                    b.OwnsOne("SkillSwap.Platform.Reputation.Domain.Model.ValueObjects.ReviewerId", "ReviewerUserId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<int>("UserId")
                                .HasColumnType("int")
                                .HasColumnName("ReviewerUserId");

                            b1.HasKey("Id");

                            b1.ToTable("reviews");

                            b1.WithOwner()
                                .HasForeignKey("Id");
                        });

                    b.Navigation("ReviewedTutorId")
                        .IsRequired();

                    b.Navigation("ReviewerUserId")
                        .IsRequired();
                });

            modelBuilder.Entity("SkillSwap.Platform.Workspace.Domain.Model.Aggregates.Session", b =>
                {
                    b.OwnsOne("SkillSwap.Platform.Workspace.Domain.Model.ValueObjects.LearnerId", "SessionLearnerId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<int>("UserId")
                                .HasColumnType("int")
                                .HasColumnName("LearnerId");

                            b1.HasKey("Id");

                            b1.ToTable("sessions");

                            b1.WithOwner()
                                .HasForeignKey("Id");
                        });

                    b.OwnsOne("SkillSwap.Platform.Workspace.Domain.Model.ValueObjects.TutorId", "SessionTutorId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<int>("UserId")
                                .HasColumnType("int")
                                .HasColumnName("TutorId");

                            b1.HasKey("Id");

                            b1.ToTable("sessions");

                            b1.WithOwner()
                                .HasForeignKey("Id");
                        });

                    b.Navigation("SessionLearnerId")
                        .IsRequired();

                    b.Navigation("SessionTutorId")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
