// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkillSwap.Platform.Shared.Infrastructure.Persistence.EntityFrameworkCore.Configuration;

#nullable disable

namespace SkillSwap.Platform.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SkillSwap.Platform.Discovery.Domain.Model.Aggregates.Tutor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Career")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<string>("MainSubject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Online")
                        .HasColumnType("tinyint(1)");

                    b.Property<double>("Rating")
                        .HasColumnType("double");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("int");

                    b.Property<string>("University")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Verified")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("tutors", (string)null);
                });

            modelBuilder.Entity("SkillSwap.Platform.Moderation.Domain.Model.Aggregates.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Closed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("reports", (string)null);
                });

            modelBuilder.Entity("SkillSwap.Platform.Moderation.Domain.Model.Aggregates.Sanction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int");

                    b.Property<int>("ReportId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("sanctions", (string)null);
                });

            modelBuilder.Entity("SkillSwap.Platform.Discovery.Domain.Model.Aggregates.Tutor", b =>
                {
                    b.OwnsOne("SkillSwap.Platform.Discovery.Domain.Model.ValueObjects.TutorId", "TutorUserId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<int>("UserId")
                                .HasColumnType("int")
                                .HasColumnName("UserId");

                            b1.HasKey("Id");

                            b1.ToTable("tutors");

                            b1.WithOwner()
                                .HasForeignKey("Id");
                        });

                    b.OwnsOne("SkillSwap.Platform.Discovery.Domain.Model.ValueObjects.TutorSkills", "TutorSkills", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<string>("Skills")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("Skills");

                            b1.HasKey("Id");

                            b1.ToTable("tutors");

                            b1.WithOwner()
                                .HasForeignKey("Id");
                        });

                    b.Navigation("TutorSkills")
                        .IsRequired();

                    b.Navigation("TutorUserId")
                        .IsRequired();
                });

            modelBuilder.Entity("SkillSwap.Platform.Moderation.Domain.Model.Aggregates.Report", b =>
                {
                    b.OwnsOne("SkillSwap.Platform.Moderation.Domain.Model.ValueObjects.ReportedUserId", "ReportedUserId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<int>("UserId")
                                .HasColumnType("int")
                                .HasColumnName("ReportedUserId");

                            b1.HasKey("Id");

                            b1.ToTable("reports");

                            b1.WithOwner()
                                .HasForeignKey("Id");
                        });

                    b.OwnsOne("SkillSwap.Platform.Moderation.Domain.Model.ValueObjects.ReporterId", "ReporterUserId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<int>("UserId")
                                .HasColumnType("int")
                                .HasColumnName("ReporterUserId");

                            b1.HasKey("Id");

                            b1.ToTable("reports");

                            b1.WithOwner()
                                .HasForeignKey("Id");
                        });

                    b.Navigation("ReportedUserId")
                        .IsRequired();

                    b.Navigation("ReporterUserId")
                        .IsRequired();
                });

            modelBuilder.Entity("SkillSwap.Platform.Moderation.Domain.Model.Aggregates.Sanction", b =>
                {
                    b.OwnsOne("SkillSwap.Platform.Moderation.Domain.Model.ValueObjects.SanctionedUserId", "SanctionedUserId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<int>("UserId")
                                .HasColumnType("int")
                                .HasColumnName("SanctionedUserId");

                            b1.HasKey("Id");

                            b1.ToTable("sanctions");

                            b1.WithOwner()
                                .HasForeignKey("Id");
                        });

                    b.Navigation("SanctionedUserId")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
