// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkillSwap.Platform.Shared.Infrastructure.Persistence.EntityFrameworkCore.Configuration;

#nullable disable

namespace SkillSwap.Platform.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SkillSwap.Platform.Moderation.Domain.Model.Aggregates.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Closed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("reports", (string)null);
                });

            modelBuilder.Entity("SkillSwap.Platform.Moderation.Domain.Model.Aggregates.Sanction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int");

                    b.Property<int>("ReportId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("sanctions", (string)null);
                });

            modelBuilder.Entity("SkillSwap.Platform.Workspace.Domain.Model.Aggregates.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("SkillSwap.Platform.Workspace.Domain.Model.Aggregates.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("SkillSwap.Platform.Moderation.Domain.Model.Aggregates.Report", b =>
                {
                    b.OwnsOne("SkillSwap.Platform.Moderation.Domain.Model.ValueObjects.ReportedUserId", "ReportedUserId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<int>("UserId")
                                .HasColumnType("int")
                                .HasColumnName("ReportedUserId");

                            b1.HasKey("Id");

                            b1.ToTable("reports");

                            b1.WithOwner()
                                .HasForeignKey("Id");
                        });

                    b.OwnsOne("SkillSwap.Platform.Moderation.Domain.Model.ValueObjects.ReporterId", "ReporterUserId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<int>("UserId")
                                .HasColumnType("int")
                                .HasColumnName("ReporterUserId");

                            b1.HasKey("Id");

                            b1.ToTable("reports");

                            b1.WithOwner()
                                .HasForeignKey("Id");
                        });

                    b.Navigation("ReportedUserId")
                        .IsRequired();

                    b.Navigation("ReporterUserId")
                        .IsRequired();
                });

            modelBuilder.Entity("SkillSwap.Platform.Moderation.Domain.Model.Aggregates.Sanction", b =>
                {
                    b.OwnsOne("SkillSwap.Platform.Moderation.Domain.Model.ValueObjects.SanctionedUserId", "SanctionedUserId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<int>("UserId")
                                .HasColumnType("int")
                                .HasColumnName("SanctionedUserId");

                            b1.HasKey("Id");

                            b1.ToTable("sanctions");

                            b1.WithOwner()
                                .HasForeignKey("Id");
                        });

                    b.Navigation("SanctionedUserId")
                        .IsRequired();
                });

            modelBuilder.Entity("SkillSwap.Platform.Workspace.Domain.Model.Aggregates.Session", b =>
                {
                    b.OwnsOne("SkillSwap.Platform.Workspace.Domain.Model.ValueObjects.LearnerId", "SessionLearnerId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<int>("UserId")
                                .HasColumnType("int")
                                .HasColumnName("LearnerId");

                            b1.HasKey("Id");

                            b1.ToTable("sessions");

                            b1.WithOwner()
                                .HasForeignKey("Id");
                        });

                    b.OwnsOne("SkillSwap.Platform.Workspace.Domain.Model.ValueObjects.TutorId", "SessionTutorId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<int>("UserId")
                                .HasColumnType("int")
                                .HasColumnName("TutorId");

                            b1.HasKey("Id");

                            b1.ToTable("sessions");

                            b1.WithOwner()
                                .HasForeignKey("Id");
                        });

                    b.Navigation("SessionLearnerId")
                        .IsRequired();

                    b.Navigation("SessionTutorId")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
